apiVersion: v1
kind: Pod
metadata:
  name: io-pod
spec:
  containers:
  - name: io-container
    image: alpine:latest
    command: ["/bin/sh", "-c"]
    args:
    - apk add --no-cache fio && fio --filename=/data/testfile --size=100m --rw=randrw --ioengine=libaio --bs=4k --direct=1 --name=io-test --runtime=60m --time_based --end_fsync=1
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
